[package]
name = "ogos_gui"
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["lib"]

[dependencies]
concat-string = { workspace = true }
const_format = { workspace = true }
crossbeam = { workspace = true }
discord-rich-presence = { workspace = true }
eframe = { workspace = true }
egui = { git = "https://github.com/bph1248/egui.git", branch = "mod", default-features = false, features = ["serde"] }
egui_extras = { git = "https://github.com/bph1248/egui.git", branch = "mod", default-features = false }
# egui = { path = "B:/dev/egui/crates/egui", default-features = false, features = ["serde"] }
# egui_extras = { path = "B:/dev/egui/crates/egui_extras", default-features = false }
fast_image_resize = { workspace = true }
hotpath = { workspace = true }
image = { workspace = true }
indexmap = { version = "2.14.0", features = ["serde"] }
jpeg-decoder = { workspace = true }
linear-srgb = { workspace = true }
log = { workspace = true }
ogos_common = { workspace = true }
ogos_config = { workspace = true }
ogos_core = { workspace = true }
ogos_discord = { workspace = true }
ogos_err = { workspace = true }
ogos_video = { workspace = true }
range-compare = "0.1.1"
raw-window-handle = "0.6.2"
resize = { workspace = true }
rfd = "0.17.2"
rgb = "0.8.52"
serde = { workspace = true }
serde_json = { workspace = true }
tap = "1.0.1"
wgpu = { workspace = true }
windows = { workspace = true }
zenwebp = { workspace = true }
zip = { workspace = true }
zune-jpeg = { workspace = true }
zune-png = { workspace = true }

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
resize = []
